PRAGMA foreign_keys=OFF;
ALTER TABLE timeline_attempts RENAME TO timeline_attempts_before_speedrun;
ALTER TABLE timeline_user_completions RENAME TO timeline_user_completions_before_speedrun;
ALTER TABLE timeline_challenges RENAME TO timeline_challenges_before_speedrun;
CREATE TABLE timeline_challenges (id TEXT PRIMARY KEY NOT NULL, challenge_date TEXT NOT NULL, difficulty TEXT NOT NULL CHECK(difficulty IN ('normal','challenge','speedrun','hardcore')), model_order_json TEXT NOT NULL, anchor_positions_json TEXT NOT NULL, tray_order_json TEXT NOT NULL, selection_version INTEGER NOT NULL, generated_at INTEGER NOT NULL, generation_source TEXT NOT NULL, UNIQUE(challenge_date,difficulty));
INSERT INTO timeline_challenges SELECT id,challenge_date,difficulty,model_order_json,anchor_positions_json,tray_order_json,selection_version,generated_at,generation_source FROM timeline_challenges_before_speedrun;
CREATE TABLE timeline_attempts (id TEXT PRIMARY KEY NOT NULL, request_id TEXT NOT NULL UNIQUE, challenge_id TEXT NOT NULL REFERENCES timeline_challenges(id) ON DELETE CASCADE, player_id TEXT NOT NULL REFERENCES anonymous_players(id) ON DELETE CASCADE, user_id TEXT REFERENCES users(id) ON DELETE SET NULL, model_order_json TEXT NOT NULL, placements_json TEXT NOT NULL, attempt_number INTEGER NOT NULL CHECK(attempt_number > 0), is_correct INTEGER NOT NULL CHECK(is_correct IN (0,1)), attempts_remaining_after INTEGER, speedrun_started_at INTEGER, speedrun_time_ms INTEGER, created_at INTEGER NOT NULL, UNIQUE(challenge_id,player_id,attempt_number));
INSERT INTO timeline_attempts (id,request_id,challenge_id,player_id,user_id,model_order_json,placements_json,attempt_number,is_correct,attempts_remaining_after,created_at) SELECT id,request_id,challenge_id,player_id,user_id,model_order_json,placements_json,attempt_number,is_correct,attempts_remaining_after,created_at FROM timeline_attempts_before_speedrun;
CREATE TABLE timeline_user_completions (user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, challenge_id TEXT NOT NULL REFERENCES timeline_challenges(id) ON DELETE CASCADE, completed_at INTEGER NOT NULL, PRIMARY KEY(user_id,challenge_id));
INSERT INTO timeline_user_completions SELECT user_id,challenge_id,completed_at FROM timeline_user_completions_before_speedrun;
DROP TABLE timeline_attempts_before_speedrun;
DROP TABLE timeline_user_completions_before_speedrun;
DROP TABLE timeline_challenges_before_speedrun;
CREATE INDEX timeline_challenges_date_idx ON timeline_challenges(challenge_date);
CREATE INDEX timeline_attempts_player_challenge_idx ON timeline_attempts(player_id,challenge_id);
CREATE INDEX timeline_attempts_user_challenge_idx ON timeline_attempts(user_id,challenge_id);
CREATE INDEX timeline_user_completions_challenge_idx ON timeline_user_completions(challenge_id);
ALTER TABLE users ADD COLUMN username TEXT;
CREATE UNIQUE INDEX users_username_idx ON users(username) WHERE username IS NOT NULL;
CREATE INDEX timeline_attempts_speedrun_leaderboard_idx ON timeline_attempts(challenge_id,is_correct,speedrun_time_ms);
PRAGMA foreign_keys=ON;
