name: Rust Unit Tests

on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string

jobs:
  test:
    name: Rust unit tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          ref: ${{ inputs.release_tag }}
      - name: Install Rust
        run: rustup toolchain install 1.94.0 --profile minimal
      - name: Run Rust unit tests
        uses: ./.github/actions/unit-test/rust
